
include:
  # - composes/compose.argus.yaml
  # - composes/compose.sisat.yaml
  - composes/compose.infra.yaml
  - composes/compose.infra.embeddings.yaml
  - composes/compose.backend_qdrant.yaml
  # - composes/compose.pipeline.cams.yaml
  
networks:
  ai_shop_assistant_network:
    name: ai_shop_assistant_network
