
include:
  # - composes/compose.argus.yaml
  # - composes/compose.sisat.yaml
  #3- composes/compose.infra.yaml
  # - composes/compose.infra.embeddings.yaml
  #- composes/compose.modules.yaml
  #- composes/compose-langfuse/langfuse.yaml
  # Project N8N
   - composes/compose-agent/compose.agent.infra.yaml
  #- composes/compose-models-llm-embedding/compose.models.llm.yaml
  
networks:
  ai_shop_assistant_network:
    name: ai_shop_assistant_network
