[project]
name = "py-exemples-lang-graph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-dotenv>=1.2.2",
    "psycopg[binary]>=3.3.3",
    "infra",
    "config",
    "langgraph>=1.1.4",
    "langchain>=1.2.15",
    "langchain-groq>=1.1.2",
    "langchain-community>=0.4.1",
    "ipykernel>=7.2.0",
    "langgraph-checkpoint-postgres>=3.0.5",
]

[tool.uv.sources]
infra = { path = "../../packages/infra", editable = true }
config = { path = "../../packages/config", editable = true }

