[project]
name = "common"
version = "0.1.0"
description = "Common shared library for microservices"
requires-python = ">=3.12"

dependencies = [
    "redis>=5.0.0",
    "pymongo>=4.0.0"
]


authors = [
    { name = "Igor Martins" }
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"