

services:
  bge_m3:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.9
    # image: ghcr.io/huggingface/text-embeddings-inference:1.9
    container_name: bge_m3
    ports:
      - "8080:80"
    volumes:
      - ../volumes/bge_m3:/data
    command:
      - --model-id
      - BAAI/bge-m3
    gpus: all
    restart: unless-stopped
    networks:
      - ai_shop_assistant_network

networks:
  ai_shop_assistant_network:
    name: ai_shop_assistant_network
