
services:


  message-aggregator:
    build:
      context: ../modules/message-aggregator-service
      dockerfile: Dockerfile
    container_name: message-aggregator
    ports:
      - "8000:8000"
    volumes:
      - ../volumes/logs:/code/logs
    environment:
      - REDIS_HOST=redis
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - ai_shop_assistant_network



  # frontend_shop_assistant:
  #   build:
  #     context: ../modules/frontend_shop_assistant
  #     dockerfile: Dockerfile
  #   container_name: frontend_shop_assistant
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NEXT_PUBLIC_API_URL: http://192.168.15.14:8010
  #   depends_on:
  #     - backend_qdrant
  #   networks:
  #     - ai_shop_assistant_network

  backend_qdrant:
    build:
      context: ../modules/backend_qdrant
      dockerfile: dockerfile
    container_name: backend_qdrant
    restart: unless-stopped
    ports:
      - "8010:8010"
    environment:
      CONTAINER_NAME: backend_qdrant

      EMBEDDING_API_BASE_URL: http://bge_m3:80
      QDRANT_URL: http://qdrant:6333
      GLOBAL_RATE_LIMIT: 20/second
      LOG_DIR: /code/logs
      SHOW_LOG: "true"
      LOG_ERROR_MODE: full

    volumes:
      - ../volumes/backend_qdrant/logs:/code/logs
    depends_on:
      - qdrant
    networks:
      - ai_shop_assistant_network

networks:
  ai_shop_assistant_network:
    name: ai_shop_assistant_network
