# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_routes/protos/model.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc_routes/protos/model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1egrpc_routes/protos/model.proto\x12\x05model\"A\n\x0cInferRequest\x12\x13\n\x0bimage_bytes\x18\x01 \x01(\x0c\x12\x1c\n\x14\x63onfidence_threshold\x18\x02 \x01(\x02\"&\n\x03RGB\x12\t\n\x01r\x18\x01 \x01(\r\x12\t\n\x01g\x18\x02 \x01(\r\x12\t\n\x01\x62\x18\x03 \x01(\r\"i\n\tClassInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x63lass_id\x18\x02 \x01(\x05\x12\x1c\n\x08ui_color\x18\x03 \x01(\x0b\x32\n.model.RGB\x12\x1e\n\nmask_color\x18\x04 \x01(\x0b\x32\n.model.RGB\"g\n\x04\x42\x42ox\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01w\x18\x03 \x01(\x02\x12\t\n\x01h\x18\x04 \x01(\x02\x12\r\n\x05label\x18\x05 \x01(\t\x12\x10\n\x08\x63lass_id\x18\x06 \x01(\x05\x12\x12\n\nconfidence\x18\x07 \x01(\x02\"\xc6\x01\n\rInferResponse\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x1e\n\tlist_bbox\x18\x02 \x03(\x0b\x32\x0b.model.BBox\x12\x1d\n\x10img_segmentation\x18\x03 \x01(\x0cH\x00\x88\x01\x01\x12$\n\nclass_list\x18\x04 \x03(\x0b\x32\x10.model.ClassInfo\x12\x18\n\x10predicted_labels\x18\x05 \x03(\t\x12\r\n\x05\x65rror\x18\x06 \x01(\tB\x13\n\x11_img_segmentation2B\n\x0cModelMethods\x12\x32\n\x05infer\x12\x13.model.InferRequest\x1a\x14.model.InferResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_routes.protos.model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERREQUEST']._serialized_start=41
  _globals['_INFERREQUEST']._serialized_end=106
  _globals['_RGB']._serialized_start=108
  _globals['_RGB']._serialized_end=146
  _globals['_CLASSINFO']._serialized_start=148
  _globals['_CLASSINFO']._serialized_end=253
  _globals['_BBOX']._serialized_start=255
  _globals['_BBOX']._serialized_end=358
  _globals['_INFERRESPONSE']._serialized_start=361
  _globals['_INFERRESPONSE']._serialized_end=559
  _globals['_MODELMETHODS']._serialized_start=561
  _globals['_MODELMETHODS']._serialized_end=627
# @@protoc_insertion_point(module_scope)
